version: '3.9'

services:
  mantap:
    container_name: api
    build:
      context: .
      dockerfile: ./mantap/depl.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mantap_db
    environment:
      DATABASE_URL: postgres://root:mantap123@database:5432/mantap?sslmode=disable
    restart: on-failure
    networks:
      - my_network

  mantap_db:
    container_name: database
    image: docker.io/library/postgres:14-alpine
    environment:
      POSTGRES_DB: mantap
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mantap123
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    external: true
