version: "3.9"

services:
  graphql:
    build:
      context: .
      dockerfile: ./graphql/depl.dockerfile

  mantap:
    build:
      context: .
      dockerfile: ./mantap/depl.dockerfile
    depends_on:
      mantap_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://root:mantap123@mantap_db:5432/mantap?sslmode=disable
    ports:
      - 8080:8080
    restart: on-failure

  mantap_db:
    build:
      context: ./mantap
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: mantap
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mantap123
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    restart: unless-stopped
