version: "3.9"

services:
  graphql:
    build:
      context: .
      dockerfile: ./graphql/depl.dockerfile

  mantap:
    build:
      context: .
      dockerfile: ./mantap/dev.dockerfile
    depends_on:
      - mantap_db
    environment:
      DATABASE_URL: postgres://root:mantap123@mantap_db:5432/mantap?sslmode=disable
    restart: on-failure

  mantap_db:
    build:
      context: ./mantap
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: mantap
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mantap123
    restart: unless-stopped
