version: '3.9'

services:
  mantap:
    build:
      context: .
      dockerfile: ./mantap/depl.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mantap_db
    environment:
      DATABASE_URL: postgres://root:mantap123@mantap_db:5432/mantap?sslmode=disable
    restart: on-failure

  mantap_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mantap
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mantap123
    ports:
      - "5432:5432"
    restart: unless-stopped
