version: '3.9'

services:
  mantap:
    container_name: api
    build:
      context: .
      dockerfile: ./mantap/depl.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mantap_db
    environment:
      DATABASE_URL: postgres://root:mantap123@mantap_db:5432/mantap?sslmode=disable
    networks:
      - my_network
    restart: always

  mantap_db:
    container_name: database
    image: docker.io/library/postgres:14-alpine
    environment:
      POSTGRES_DB: mantap
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mantap123
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  my_network:
    external: true

volumes:
  db_data:
